# Generated by Django 6.0.1 on 2026-01-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='Line ID')),
                ('address_detail', models.TextField(blank=True, verbose_name='ที่อยู่เพิ่มเติม')),
                ('budget', models.CharField(choices=[('2.01-2.50', '2.01-2.50 ล้านบาท'), ('2.51-3.00', '2.51-3.00 ล้านบาท'), ('3.01-3.50', '3.01-3.50 ล้านบาท'), ('3.51-4.00', '3.51-4.00 ล้านบาท'), ('4.01-4.50', '4.01-4.50 ล้านบาท'), ('4.51-5.00', '4.51-5.00 ล้านบาท'), ('5.00+', 'มากกว่า 5.00 ล้านบาท')], max_length=20, verbose_name='งบประมาณ')),
                ('preferred_day', models.CharField(choices=[('weekday', 'วันทำการ (จันทร์-ศุกร์)'), ('weekend', 'วันหยุด (เสาร์-อาทิตย์)')], max_length=10, verbose_name='วันที่สะดวก')),
                ('preferred_time', models.CharField(choices=[('09:00-12:00', 'ช่วงเช้า (09.00-12.00)'), ('12:00-13:00', 'ช่วงเที่ยง (12.00-13.00)'), ('13:00-15:00', 'ช่วงบ่าย (13.00-15.00)'), ('15:00-18:00', 'ช่วงเย็น (15.00-18.00)'), ('18:00-21:00', 'ช่วงค่ำ (18.00-21.00)')], max_length=20, verbose_name='เวลาที่สะดวก')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='ติดต่อแล้ว')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district', verbose_name='เขต/อำเภอ')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province', verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': 'ข้อมูลลูกค้า',
                'verbose_name_plural': 'ข้อมูลลูกค้า',
                'ordering': ['-created_at'],
            },
        ),
    ]
