# Generated by Django 6.0.1 on 2026-01-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=150, verbose_name='ชื่อจังหวัด (ไทย)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ชื่อจังหวัด (อังกฤษ)')),
                ('geography_id', models.IntegerField(blank=True, null=True, verbose_name='รหัสภูมิภาค')),
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัด',
                'ordering': ['name_th'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=150, verbose_name='ชื่อเขต/อำเภอ (ไทย)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ชื่อเขต/อำเภอ (อังกฤษ)')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.province', verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': 'เขต/อำเภอ',
                'verbose_name_plural': 'เขต/อำเภอ',
                'ordering': ['name_th'],
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=150, verbose_name='ชื่อแขวง/ตำบล (ไทย)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ชื่อแขวง/ตำบล (อังกฤษ)')),
                ('zip_code', models.CharField(max_length=5, verbose_name='รหัสไปรษณีย์')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='locations.district', verbose_name='เขต/อำเภอ')),
            ],
            options={
                'verbose_name': 'แขวง/ตำบล',
                'verbose_name_plural': 'แขวง/ตำบล',
                'ordering': ['name_th'],
            },
        ),
    ]
